<a href="https://colab.research.google.com/github/mabubakar-here/Gemini-bot/blob/main/Week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensor

### creating tensor


In [2]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python init
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor ([[[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors
why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and thn adjust those numbers to better represent the data.

'start with random number -> look at data -> update random numbers -> look at data -> update random numbers'

In [15]:
# Create random tensor  of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8398, 0.3919, 0.9946, 0.5501],
        [0.6075, 0.4428, 0.2132, 0.7267],
        [0.8167, 0.7808, 0.6524, 0.0320]])

In [16]:
random_tensor.ndim

2

In [17]:
# Create a random tensor with the size of an image
random_image_size_tensor = torch.rand(3, 224, 224) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Ranom Tensors with zeros and ones

In [18]:
# Creating tensor with all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Creating tensors of all ones

ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype


torch.float32

### Creating Range of Tensors and Tensors-like

In [22]:
one_to_ten = torch.arange(start= 0, end= 1000, step= 77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [23]:
torch_like = torch.zeros_like(input= one_to_ten)
torch_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Note:** Tensor datatye is one of the 3 big errors you'll run into with Pytorch and deep learning
1. Tensors not right datatype
2. Tensors not on the right shape
3. Tensors not on the right device

In [24]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0] ,
                               dtype = None, # what datatype is the tensor (e.g float32, float)
                               device = None, # On what device the tensor is (i.e cpu, gpu)
                               requires_grad= False) # wether to track gradient or not
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting Information from the tensor

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not on the right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`



In [27]:
# Creating a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9234, 0.8316, 0.8140, 0.1870],
        [0.4694, 0.6621, 0.8562, 0.9037],
        [0.9140, 0.4154, 0.9315, 0.1680]])

In [28]:
# find out details about rendom tensor
print("some_tenosr")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of a tensor: {some_tensor.shape}")
print(f"dveice of a tensor: {some_tensor.device}")

some_tenosr
Datatype of tensor: torch.float32
shape of a tensor: torch.Size([3, 4])
dveice of a tensor: cpu


###Manuplating Tensor

Thensor operation include
1. Addition
2. Subtraction
3. Multiplication (element wise)
4. Division
5. Matrix Multiplication

In [29]:
 # Creating a tensor and adding a tensor
 tensor = torch.tensor([1, 2, 3])
 tensor + 10

tensor([11, 12, 13])

In [30]:
# Multiplying a tensor
tensor * 10

tensor([10, 20, 30])

In [31]:
tensor - 10

tensor([-9, -8, -7])

In [32]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [33]:
# Try out tensor in-built fuctions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways to perform multiplication in neural netwrok and deep learning
 1). Element wise multiplication
 2). Matrix Multiplication (dot product)


In [34]:
#Element wise multiplication
print ( tensor, "*", tensor)
print(tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [35]:
# Matrix multiplication
torch.matmul( tensor, tensor)

tensor(14)

### Shapes for matarix multiplication

To fix our shape issue, we can manuplate  the shape of one of our tensors using **transpose**

A **transpose** switched the axes or dimensions of given tensor

In [36]:
tensor_A = torch.tensor([[4, 6],
                        [4, 5],
                        [2, 6]])

tensor_B = torch. tensor([[3, 5],
                          [5, 6],
                          [2, 7]])

torch.matmul(tensor_A, tensor_B.T)

tensor([[42, 56, 50],
        [37, 50, 43],
        [36, 46, 46]])

Finding the min, max, mean, sum etc (tensor aggereation)

In [37]:
#Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [38]:
#Finding the min
torch.min(x), x.min()


(tensor(1), tensor(1))

In [39]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [40]:
#Finding the mean - note: torch.mean funcion requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [41]:
# Finding the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

###Finding the positional min & max


In [42]:
### Find the position in the tensor that has the minimum value with argmin()-> return index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [43]:
x[0]

tensor(1)

In [44]:
x.argmax()

tensor(9)

In [45]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing, and unsqueezing
* Reshaping  - reshape a a defined tensor to a defined shape
* View - Return the view of an input tensor of the certain shape but the keep the same in the memory as the orignal tensor
* Stacking - combine multiple tensor on top of each other (vstack)
* Squeeze - removes all '1' dimension from the tensor.
* Unsqueeze - add all '1' dimension to the target tensor
* Permute - Return the view of the input with dimension permuted (swaped) in a certain way.

In [46]:
# Create a tensor
x = torch.arange(1. , 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [47]:
# Add an extra dimenshion
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [48]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [49]:
# Changing z changes x (becase view of tensor shares the same memory as the orignal tensor shares)
z[:, 0] = 5
x, z

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [50]:
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [51]:
# torch.squeeze() - removes all single dimension form the targeted tensor
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [52]:
# torch.unsqueeze() - add a single dimension in the targeted tensor at a specific dim (dimension)
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# add an extra dimension with unsqueeze
x_squeezed = x_reshaped.squeeze()
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [53]:
# torch.permute - rearrange the dimension of a targeted tensor in a specified order
x_orignal = torch.rand(224, 224, 3) # hight, width and color_channels

# Permute the orignal tenosor to rearrange the axis(or dimension) order
x_permuted = x_orignal.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_orignal.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (Selecting data from tensors)
Indexing with pytorch is similar to NumPy

In [54]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [55]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [56]:
# Let's index on our middle bracket (dim=1)
x[0, 0]

tensor([1, 2, 3])

In [57]:
#Let's index on the most inner bracket (dim 2)
x[0][1][2]

tensor(6)

In [58]:
#You can also you ":" to select "all" of the targeted tensor
x[:, 0]

tensor([[1, 2, 3]])

In [59]:
#get all values of 0th ang 1st dimension but index 1 of 2nd dimension
x[:, :, 2]

tensor([[3, 6, 9]])

### Pytorch & NumPy
Numpy is poppular scientific numerical computing library. And because of this Pytorch has functionality to interact with it.
* Data in NumPy, want in Pytorch tensor -> 'torch.from_numpy(ndarray)'
* Pytorch tensor-> Numpy -> 'torch.Tensor.numpy()'

In [60]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # When converting from numpyt to pytorch, Pytorch will reflect default numpy data type of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [61]:
# Change the value of array
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [62]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility(trying to take random out of random)
In short how nerual networks work:
start with random numbers -> tensor operations -> update random numbpers to make them better representation of the data -> again -> again -> again......

To reduce the randomness in neural networks and Pytorch comes the concep to a **Random Seed**

Essentially what the random seed does is "flavor" the randomness.


In [63]:
#Create 2 random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5079, 0.4693, 0.5024, 0.6196],
        [0.6802, 0.0070, 0.7766, 0.5772],
        [0.3572, 0.8186, 0.0392, 0.2166]])
tensor([[0.5278, 0.8600, 0.5363, 0.0249],
        [0.1477, 0.5738, 0.5431, 0.6731],
        [0.1691, 0.9343, 0.0551, 0.8363]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [64]:
# Let's make some rendom tensors but reproducible seeds
# Set the random seed
Random_Seed = 42
torch.manual_seed(Random_Seed)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(Random_Seed)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running Pytorch objects and tensors using GPU's (and making faster computations)

GPU = faster computation on numbers

#Gettinga  GPU
* Easiest = Use google colab for a free GPU
* Use your own GPU. It requires a bit setup and requires an investment of purchasing a GPU there's a lot of options....
* Use cloud computing- GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

* For 2, 3 Pytorch + GPU drivers (CUDA) takes a little bit of setting up, to do this refers to pytorch setup documentation

### Check for GPU access on Pytorch

In [71]:
#Check for GPU access in Pytoch
torch.cuda.is_available()

True

In [72]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [66]:
# count the gpu's using Pytorch
torch.cuda.device_count()

1

### Putting Tensor (and models) on the GPU
Reason to prefer GPU is fast computation

In [73]:
#Creating a tensor (default on cpu)
tensor = torch.tensor([1, 2, 3])

#Tensor of cpu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [74]:
 tensor_on_gpu = tensor.to(device)
 tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensor back to cpu

In [78]:
cpu_device = "cpu" if not torch.cuda.is_available() else "cuda"

In [79]:
tensor_on_gpu = tensor.to(cpu_device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')