<a href="https://colab.research.google.com/github/mabubakar-here/Gemini-bot/blob/main/Week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensor

### creating tensor


In [2]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python init
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor ([[[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random Tensors
why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and thn adjust those numbers to better represent the data.

'start with random number -> look at data -> update random numbers -> look at data -> update random numbers'

In [15]:
# Create random tensor  of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9740, 0.5670, 0.5020, 0.6847],
        [0.5703, 0.7049, 0.5417, 0.7562],
        [0.6192, 0.8958, 0.4909, 0.6665]])

In [16]:
random_tensor.ndim

2

In [17]:
# Create a random tensor with the size of an image
random_image_size_tensor = torch.rand(3, 224, 224) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Ranom Tensors with zeros and ones

In [18]:
# Creating tensor with all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Creating tensors of all ones

ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype


torch.float32

### Creating Range of Tensors and Tensors-like

In [22]:
one_to_ten = torch.arange(start= 0, end= 1000, step= 77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [23]:
torch_like = torch.zeros_like(input= one_to_ten)
torch_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Note:** Tensor datatye is one of the 3 big errors you'll run into with Pytorch and deep learning
1. Tensors not right datatype
2. Tensors not on the right shape
3. Tensors not on the right device

In [24]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0] ,
                               dtype = None, # what datatype is the tensor (e.g float32, float)
                               device = None, # On what device the tensor is (i.e cpu, gpu)
                               requires_grad= False) # wether to track gradient or not
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting Information from the tensor

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not on the right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`



In [27]:
# Creating a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2260, 0.8120, 0.4992, 0.9616],
        [0.2929, 0.8118, 0.5684, 0.9859],
        [0.1865, 0.6527, 0.4526, 0.8928]])

In [28]:
# find out details about rendom tensor
print("some_tenosr")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"shape of a tensor: {some_tensor.shape}")
print(f"dveice of a tensor: {some_tensor.device}")

some_tenosr
Datatype of tensor: torch.float32
shape of a tensor: torch.Size([3, 4])
dveice of a tensor: cpu


###Manuplating Tensor

Thensor operation include
1. Addition
2. Subtraction
3. Multiplication (element wise)
4. Division
5. Matrix Multiplication

In [29]:
 # Creating a tensor and adding a tensor
 tensor = torch.tensor([1, 2, 3])
 tensor + 10

tensor([11, 12, 13])

In [30]:
# Multiplying a tensor
tensor * 10

tensor([10, 20, 30])

In [31]:
tensor - 10

tensor([-9, -8, -7])

In [32]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [33]:
# Try out tensor in-built fuctions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways to perform multiplication in neural netwrok and deep learning
 1). Element wise multiplication
 2). Matrix Multiplication (dot product)


In [34]:
#Element wise multiplication
print ( tensor, "*", tensor)
print(tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [35]:
# Matrix multiplication
torch.matmul( tensor, tensor)

tensor(14)

### Shapes for matarix multiplication

To fix our shape issue, we can manuplate  the shape of one of our tensors using **transpose**

A **transpose** switched the axes or dimensions of given tensor

In [36]:
tensor_A = torch.tensor([[4, 6],
                        [4, 5],
                        [2, 6]])

tensor_B = torch. tensor([[3, 5],
                          [5, 6],
                          [2, 7]])

torch.matmul(tensor_A, tensor_B.T)

tensor([[42, 56, 50],
        [37, 50, 43],
        [36, 46, 46]])

Finding the min, max, mean, sum etc (tensor aggereation)

In [37]:
#Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [38]:
#Finding the min
torch.min(x), x.min()


(tensor(1), tensor(1))

In [39]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [40]:
#Finding the mean - note: torch.mean funcion requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [41]:
# Finding the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

###Finding the positional min & max


In [42]:
### Find the position in the tensor that has the minimum value with argmin()-> return index position of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [43]:
x[0]

tensor(1)

In [44]:
x.argmax()

tensor(9)

In [45]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing, and unsqueezing
* Reshaping  - reshape a a defined tensor to a defined shape
* View - Return the view of an input tensor of the certain shape but the keep the same in the memory as the orignal tensor
* Stacking - combine multiple tensor on top of each other (vstack)